version: "2"
run:
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gocyclo
    - misspell
    - revive
    - govet
    - gosec
    - staticcheck
formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
