name: pr-checks
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: run checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
      - name: install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
        shell: bash
      - name: run govulncheck
        run: govulncheck -show verbose ./...
        shell: bash
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: 'v1.57'
          skip-cache: true
